# Generated by Django 4.2 on 2023-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='such as Ewedu Efo', max_length=50, verbose_name='Add on NAme')),
                ('image', models.ImageField(blank=True, null=True, upload_to='addon', verbose_name='Images of The Add-on Goods')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AddonGoods',
                'verbose_name_plural': 'AddonGoodss',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='addon',
            field=models.ManyToManyField(to='app.addongoods'),
        ),
    ]
