# Generated by Django 4.2 on 2023-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_addongoods_options_remove_good_addon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addongoods',
            name='food',
        ),
        migrations.AddField(
            model_name='addongoods',
            name='food',
            field=models.ManyToManyField(to='app.good'),
        ),
    ]
