# Generated by Django 4.2 on 2023-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_addongoods_food_addongoods_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addongoods',
            name='food',
        ),
    ]
