# Generated by Django 4.2 on 2023-11-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_addongoods_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryPackages',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deliveryPackages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='app.deliverypackages'),
        ),
    ]
