# Generated by Django 4.2 on 2023-11-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orderitem_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addongoods',
            name='name',
            field=models.CharField(help_text='such as Ewedu Efo', max_length=250, verbose_name='Add on Name'),
        ),
    ]
