# Generated by Django 4.2 on 2023-11-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_addongoods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypackages',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='The Price for The Package in Naira'),
        ),
    ]
