# Generated by Django 4.2 on 2023-11-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_deliverypackages_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='deliveryPackages',
            new_name='delivery',
        ),
    ]
