# Generated by Django 4.2 on 2023-11-19 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_deliverypackages_orderitem_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='delivery', to='app.deliverypackages'),
        ),
    ]
