# Generated by Django 4.2 on 2023-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='addon',
            field=models.BooleanField(default=False, verbose_name='Does The Food comes With othe Items'),
        ),
    ]
