# Generated by Django 4.2 on 2023-11-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_good_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Amount Paid for Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='package_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Amount Paid For Package'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Amount Paid For Tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Amount Paid For Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Amount Paid for Total'),
        ),
    ]
