# Generated by Django 4.2 on 2023-11-24 18:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_good_delivery_alter_good_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of The food')),
                ('image', models.ImageField(upload_to='plugin', verbose_name='Images of The Food')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='The Price for The Package in Naira')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PluginFoods',
                'verbose_name_plural': 'PluginFoodss',
            },
        ),
        migrations.CreateModel(
            name='PluginOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pluginfoods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PluginOrderItem',
                'verbose_name_plural': 'PluginOrderItems',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plugin',
            field=models.ManyToManyField(to='app.pluginorderitem'),
        ),
    ]
