# Generated by Django 4.2 on 2023-11-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_pluginfoods_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='app.deliverypackages'),
        ),
    ]
