# Generated by Django 4.2 on 2023-11-30 23:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
